#
# Module manifest for module 'Qlik-Cli'
#
# Generated by: Adam Haydon
#
# Generated on: 16/08/2017
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule = 'Qlik-Cli.psm1'

    # Version number of this module.
    ModuleVersion = '0.0.0'

    # ID used to uniquely identify this module
    GUID = '730275fa-35db-42e2-9400-eac7e3043ea4'

    # Author of this module
    Author = 'Adam Haydon'

    # Company or vendor of this module
    CompanyName = 'Qlik'

    # Copyright statement for this module
    Copyright = '(c) 2017 Qlik. All rights reserved.'

    # Description of the functionality provided by this module
    Description = 'This module contains cmdlets to manage Qlik Sense'

    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '4.0'

    # Name of the Windows PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the Windows PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of Microsoft .NET Framework required by this module
    # DotNetFrameworkVersion = ''

    # Minimum version of the common language runtime (CLR) required by this module
    # CLRVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module
    # RequiredModules = @()

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    NestedModules = @('resources\about.ps1', 'resources\app.ps1', 'resources\certificate.ps1', 'resources\content.ps1', 'resources\customproperty.ps1', 'resources\dataconnection.ps1', 'resources\engine.ps1', 'resources\extension.ps1', 'resources\node.ps1', 'resources\license.ps1', 'resources\object.ps1', 'resources\privileges.ps1', 'resources\proxy.ps1', 'resources\rule.ps1', 'resources\scheduler.ps1', 'resources\servicecluster.ps1', 'resources\servicestatus.ps1', 'resources\session.ps1', 'resources\stream.ps1', 'resources\table.ps1', 'resources\tag.ps1', 'resources\task.ps1', 'resources\user.ps1', 'resources\userdirectory.ps1', 'functions\core.ps1', 'functions\helper.ps1', 'functions\util.ps1')

    # Functions to export from this module
    FunctionsToExport = 'Add-Qlik*', 'Assert-Qlik*', 'Connect-Qlik', 'Copy-Qlik*', 'Export-Qlik*', 'Get-Qlik*', 'Import-Qlik*', 'Invoke-Qlik*', 'New-Qlik*', 'Publish-Qlik*', 'Register-Qlik*', 'Remove-Qlik*', 'Restore-Qlik*', 'Select-Qlik*', 'Set-Qlik*', 'Start-Qlik*', 'Stop-Qlik*', 'Switch-Qlik*', 'Sync-QlikUserDirectory', 'Unpublish-Qlik*', 'Update-Qlik*', 'Wait-Qlik*'

    # Cmdlets to export from this module
    CmdletsToExport = ''

    # Variables to export from this module
    VariablesToExport = ''

    # Aliases to export from this module
    AliasesToExport = 'Export-QlikCertificates', 'Get-QlikAnalyserAccessType', 'Get-QlikLoginAccess', 'Qonnect', 'Remove-QlikAnalyserAccessType'

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = 'Qlik', 'Sense', 'PSEdition_Desktop', 'PSEdition_Core', 'Windows', 'Linux', 'MacOS'

            # A URL to the license for this module.
            LicenseUri = 'https://github.com/ahaydon/Qlik-Cli-Windows/blob/master/LICENSE'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/ahaydon/Qlik-Cli-Windows'

            # A URL to an icon representing this module.
            # IconUri = ''

            # ReleaseNotes of this module
            # ReleaseNotes = ''

        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''

}
