# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'json'

if File.exists?(File.expand_path "./config.json")  
    config = JSON.parse(File.read(File.expand_path "./config.json"))
end
servers = config["servers"]

Vagrant.configure(2) do |config|
  servers.each do |attr|
    config.vm.define attr["name"] do |srv|
      srv.vm.box = attr["box"]
      srv.vm.communicator = "winrm"
      srv.vm.graceful_halt_timeout = 120
      srv.vm.network "private_network", virtualbox__intnet: true, ip: attr["ip"]
      attr["ports"].each do |port|
        srv.vm.network "forwarded_port", guest: port["guest"], host: port["host"]
      end
      srv.vm.hostname = attr["name"]
      srv.vm.provision "file", source: "../Qlik-Cli.psm1", destination: "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\Modules\\Qlik-Cli\\Qlik-Cli.psm1", run: "always"
      srv.vm.provision "file", source: "../dsc/modules/QlikResources.psm1", destination: "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\Modules\\QlikResources\\QlikResources.psm1", run: "always"
      srv.vm.provision "file", source: "../dsc/modules/QlikResources.psd1", destination: "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\Modules\\QlikResources\\QlikResources.psd1", run: "always"
      srv.vm.provision "file", source: "../dsc/manifests/QlikConfig.ps1", destination: "QlikConfig.ps1", run: "always"
      srv.vm.provision "file", source: "../dsc/manifests/SiteConfig.psd1", destination: "SiteConfig.psd1", run: "always"
      srv.vm.provision :shell, path: "provision.ps1"
    end
  end
end
